# Generated by Django 3.2.12 on 2022-07-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220715_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='message',
        ),
    ]
